### ISSUE TITLE
ProDOS 2.5.0a3 and ProTerm 3.1 - garbage after volume names

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#12]
ProDOS 2.5.0a3 and ProTerm 3.1 - garbage after volume names

BUG

2.5
## Description

I noticed when selecting a file for upload in ProTerm 3.1 that if I go up to the top level the volume names are shown with some garbage on the end.  I think this bug was also filed for some other program that doesn't respect the length byte for the volume name string.

## Expected Behavior

Volume names should be shown without trailing garbage.

## Actual Behavior

A few characters of rubbish are shown after the end of eavh volume name.  Volumes can still be selected without problem.

## Steps to Reproduce

1. Boot ProDOS 2.5.0a3
2. Run ProTerm 3.1
3. Use the Send menu to upload a file
4. In the file picker, keep selecting '..' until you are at the very top.
5. Behold!

## Context

Impact seems minor.

### Hardware:

Apple //e Enhanced 128K
MicroDrive/Turbo in slot 7.

### ProDOS8 version:
2.5.0a3

### Non-Operating System release software being used: 
ProTerm 3.1

**Comment by JohnMBrooks** [comment]
Please see if you can repro this issue using ProDOS 2.4.2, to find out when this problem started.

**Comment by bobbimanners** [comment]
This issue is not seen in ProDOS 2.4.2.

**Comment by JohnMBrooks** [comment]
Fixed in P8 2.5.0a4.
