### ISSUE TITLE
ProDOS 2.5.0a3 and Apple2Pi v1.6 - No PiDrive!

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#14]
When I run Apple2Pi v1.6 under ProDOS 2.5.0a3 the PiDrives are not mounted

BUG

2.5
## Description

David Schmenk's Apple II Pi software has a built in protocol for serial drives.  This is similar to the VSDRIVE feature of ADTPro, but uses a simpler protocol.  The A2Pi implementation is called PiDrive.

I have the A2Pi server set up to serve two PiDrives.  When I boot Prodos 2.4.2 and run the STARTUP program for the A2Pi client version 1.6, the software tells me there are PiDrives on S2D1 and S2D2.  Pressing Open-Apple - Closed-Apple - Delete to escape from the A2Pi client drops us back into BASIC and CAT,S2,D1 works as expected.

Booting ProDOS 2.5.0a3, A2Pi seems to work as normal except the PiDrives are not mounted.  no message about the PiDrives is shown when the A2Pi client starts.

## Expected Behavior

PiDrives should be available on slot 2.

## Actual Behavior

But they aren't!

## Steps to Reproduce

1. Boot ProDOS 2.5.0a3
2. Make sure the Apple II Pi server is running and the serial cable is connected etc.
3. Run the STARTUP program for the Apple II Pi client (v1.6)
4. See if the message about the PiDrives is shown or not.

## Context

Was trying to use the PiDrive to copy an 800K floppy image to my HDD.

### Hardware:

Apple //e Enhanced 128K
MicroDrive/Turbo in slot 7
Disk II in slot 6
SPAOE Z80 in slot 4
SSC in slot 2
Parallel in slot 1

### ProDOS8 version:
2.5.0a3

### Non-Operating System release software being used: 
Apple II Pi version 1.6

**Comment by JohnMBrooks** [comment]
It is likely that ProDOS device drivers will need modification to be compatible with ProDOS 2.5.0.

**Comment by bobbimanners** [comment]
I guess this will affect ADTPro's VDDRIVE too then.  I haven't tried that one yet though.

Hopefully the two Davids (Schmitt and Schmenk) will be able to update their respective device drivers.

**Comment by david-schmidt** [comment]
@david-schmidt Tagging for awareness

**Comment by JohnMBrooks** [comment]
PiDrive works with P8 2.5.0 after being patched to fix these issues:
1) hardcoded address of P8 null device driver instead of using slot 0 null driver address
2) hardcoded limit of 14 devices in devlst instead of using 0 as end of devlst
3) sets bit 0 of inserted device num instead of keeping low 4 bits zeroed
