### ISSUE TITLE
Maybe we need a byte to turn on/off lowercase support for a volume

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#16]
Maybe we need a switch to turn on/off lowercase support?

BUG

2.5
## Description

Kyan Pascal (for example) handles the case of filenames in a weird way.  Most likely there are other apps that do similarly broken things.  In the case of Kyan, the `ls` command shows all filenames in lower case regardless of their actual case on disk.  The possible regression I am noticing here is suppose I have the file `TEST.P` on disk, with an upper-case filename, and then compile it the normal way: `pc test.p`, I end up with an executable called `test` rather than `TEST`.  It seems Kyan lower-cases everything internally (I have no yet confirmed that) so there is no way to `mv test TEST` in the `KIX.SYSTEM` shell.  I can, of course, start BASIC and `REN test,TEST` and all is well.

For reasons like this, I am in two minds about the lower case filename support.  I wonder if it would be nice to be able to turn it off on a per volume basis.  Is there a spare byte somewhere that could be used to enable/disable support for lowercase filenames?

## Expected Behavior

It would be nice to be able to obtain consistent behaviour with arguably broken legacy apps.

## Actual Behavior

In Kyan at least, compiling old source files with uppercase names gives lowercase names for the executables.  It looks okay from within Kyan, but Bitsy Bye shows the true case is inconsistent.

## Possible Fix

I would like to be able to turn lower case support off for a volume, to avoid this kind of thing.

## Steps to Reproduce

See description.

## Context

I am a neat freak with my disks, so having a mixture of case is a mess.  And I can't easily fix it (or even see it) without quitting Kyan.  There are very few tools I can use to fix this.  Renaming them one at a time in BASIC is a bit tedious.

## Your Environment

Apple //e Enhanced

### ProDOS8 version:
2.5.0a3

### Non-Operating System release software being used: 
Kyan Pascal

**Comment by JohnMBrooks** [comment]
I can see if this is possible, but it may be better to fix the apps. It is likely that apps will need minor changes to fix the date format problem(s) (Y2028 & Y2040), and lowercase name issues like this.

**Comment by JohnMBrooks** [comment]
I quickly tested Kyan file creation. Found that cp, mv, mkdir and editor file operations correctly send mixed-case filenames to ProDOS 2.5.

The problem appears to be that Kix displays volume names in uppercase and filenames in lowercase rather than using the mixed-case names provided by ProDOS 2.5.

My preference would be to mod Kix so it displays the mixed case provided by ProDOS 2.5, and possibly create a new kix command to rename a file to uppercase if desired.

**Comment by JohnMBrooks** [comment]
Here is a patch to 'ls' so it correctly displays mixed-case filenames in ProDOS 2.5:
bload ls
mtr
d16:00
bsave ls,A$800,L7699

**Comment by bobbimanners** [comment]
I didn't have any luck patching the Kyan `ls` command.  After I change the byte in the monitor, doing the `BSAVE` just hangs.  Can you double check the instructions above?

Edit: My bad - I was quitting the monitor with `^B` which seems to mess up ProDOS.  `^C` works better!

**Comment by bobbimanners** [comment]
Maybe I am doing something stupid.  I run `BASIC.SYSTEM` then:

`PREFIX KYAN.PASCAL/BIN`
`BLOAD LS`
`MTR`
`^B` to quit monitor (no changes made)
`CAT`

And the `CAT` command hangs.  I didn't even change the `ADC #$20` to `ADC #$00`.  Seems entering the monitor and leaving is messing up ProDOS.  Should I quit the monitor some other way?  ^B, ^C, jump to some address?

**Comment by bobbimanners** [comment]
The patch to `ls` seems to work :)

I will play around some more and see if there are any rough edges.

Incidentally, I see that Kyan has an option in the `cfg` program to enable or disable lower case.  I tried changing this setting and it didn't appear to have any effect, but it would be good to know what it does / is supposed to do.
