### ISSUE TITLE
Renaming a certain directory causes disk corruption with 2.5.0a3

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#17]
Renaming a certain directory causes disk corruption with 2.5.0a3

BUG

2.5
## Description

This is a bit of strange issue, and I have been having trouble nailing it down completely.  At present I can only make it happen on an HDD partition.  I am trying to reproduce this using GSPort rather than a real physical Apple II, but I can try on real hardware later if needed.

The issue is with renaming a particular directory.  This occurred on an HDD Image renaming the directory `VISICALC.ADV`, which contains the files copied from the [800k image of Visicalc Advanced found on Asimov](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/spreadsheet/Visicalc%20Advanced.po)

Renaming this directory using `BASIC.SYSTEM` `RENAME` trashes the directory so that the BASIC `CAT` command can no longer list the contents.  Strangely, it still looks OK in Bitsy Bye but any attempt to launch a SYSTEM file in the directory using Bitsy Bye silently fails.

I tried the same steps in ProDOS 2.4.2 without any problems.  This seems to be an issue introduced in 2.5.0.

I also nailed this down to one particular file `HELP.TEXT.FILE`.  If I create a directory with just that file in it and then rename it in BASIC under 2.5.0a3, the directory is corrupted.

`MR.FIXIT.Y2K` can fix the damage.  It complains about the directory length I think.

## Expected Behavior

Rename shouldn't corrupt the disk!

## Actual Behavior

Renaming a directory with this particular file causes corruption.

## Steps to Reproduce

1. Download the Visicalc Advanced 800k disk image.
2. On an HDD image, create a directory and copy the files from the floppy there.
3. Under ProDOS 2.5.2 run `BASIC.SYSTEM`
4. `RENAME MYDIRECTORY,SOMENEWNAME`
5. `CAT SOMENEWNAME`
6. No files are seen, or sometimes corrupt garbage is shown.

## Context

Wanted to rename my directory :)

## Your Environment

GSPort version v0.31 on Ubuntu 19.04

### Hardware:

Emulated Apple II GS with ROM03.

### ProDOS8 version:
2.5.0a3

### Non-Operating System release software being used: 
Visicalc Advanced floppy - don't need to run it, just need the file(s).

**Comment by bobbimanners** [comment]
I wasn't successful in an attempt to reproduce this on an 800K floppy image, by the way.

**Comment by bobbimanners** [comment]
I had this happen again today, on a MicroDrive/Turbo volume, and I have some additional snippets of information.  I renamed the directory using the Aztec C64 `SHELL.SYSTEM` this time, just to mix it up a bit ;)

I did the following `cd /h1`, then `mv prodos.2.5.0a3 prodos.2.5.0a31`.  Following that the catalog of the renamed directory seemed to be totally messed up when viewed using the `ls` command of Aztec C.  The same file appeared for each of the expected entries (ie: I think it was the same number as the actual number of entries in the catalog, but the name was actually the directory name replicated for each entry.)

Quit from Aztec C shell and went and had a look using Bitsy Bye.  Surprise!  The catalog looks fine.  How odd?

Ran `MR.FIXIT.Y2K` and it fixed the corruption.  The report was: "Entry length fixed" and "Entries/block fixed".

So there is something fishy with renaming directories.

**Comment by JohnMBrooks** [comment]
Please see if you can make a repro case for this with 2.5.0a4.
https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP

**Comment by bobbimanners** [comment]
I have confirmed that this still happens on 2.5.0a4.  I am able to reproduce this on a hard drive partition (32MB partition on MicroDrive/Turbo) but I can't make it happen on a 143K Disk II floppy.

Steps to reproduce using BASIC:

`prefix /h1` -- HDD volume
`create mydir`
`create mydir/a`
`create mydir/b`
`create mydir/c`
`cat mydir` -- Everything looks fine.
`rename mydir,mydir2`
`cat mydir2` -- Catalog is empty.

**Comment by JohnMBrooks** [comment]
Please try to repro this in a5

**Comment by bobbimanners** [comment]
Doesn't seem to happen in alpha 5.
