### ISSUE TITLE
Regression: ProTerm 3.1 doesn't start with ProDOS 2.5.0a4

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#19]
Regression: ProTerm 3.1 doesn't start with ProDOS 2.5.0a4

BUG

2.5
## Description

Under ProDOS 2.5.0a4, ProTerm 3.1 will not start.  It complains "An error occurred accessing: /H1/PROTERM.3.1/pt3.bios".  Note the mixed case in the message.

This works under 2.5.0a3 release 2, so it is a recent regression.
## Expected Behavior

ProTerm 3.1 should start.

## Actual Behavior

Error dialog shown instead.

## Steps to Reproduce

1. Run `PR3.SYSTEM`
2. Observe the error dialog
3. Reboot into 2.5.0a3 release 2
4. Run `PT3.SYSTEM`
5. All is well.

## Context

Was planning on regression testing the issue with the trailing garbage after the volume names.

### Hardware:

Apple //e Ehhaanced 128k.  MicroDrive/Turbo.

### ProDOS8 version:
2.5.0a4

### Non-Operating System release software being used: 
ProTerm 3.1

**Comment by JohnMBrooks** [comment]
Good catch. Now fixed.
https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP

**Comment by bobbimanners** [comment]
Confirmed fixed in the latest 2.5.0a4 ... 2.5.0a4r2 let's call it :)
