### ISSUE TITLE
ProDOS 2.5.0a5 Bitsy Bye Number Key Issue

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#22]
ProDOS 2.5.0a5 Bitsy Bye Number Key Issue

BUG

2.5
## Description

I have a MicroDrive/Turbo with four partitions.  With the new enhancements in ProDOS 2.5.0 alpha 5, all four partitions are mapped to slot 7.  However this works a bit wrong in Bitsy Bye.

- Suppose I am looking at S7,D1 to start with.
- Press '7' - now it is S7,D2
- Press '7' - now it is S7,D3
- Press '7' - now it is S7,D4
- Press '7' - now it goes to S6,D1 for some reason.

## Expected Behavior

Should loop back to S7,D1.

## Actual Behavior

Goes to another slot.

## Steps to Reproduce

1. Boot 2.5.0 alpha 5 with a HDD with four partitions.
2. Run `QUIT.SYSTEM`
3. Hit the '7' key to cycle through the partitions.

## Context

Alpha testing 2.5.0

### Hardware:

Apple IIe Enhanced, 128K
Slot 7: MicroDrive/Turbo with four partitions set up
Slot 6: Disk ][ controller and two drives

### ProDOS8 version:
2.5.0 alpha 5

### Non-Operating System release software being used: 
None

**Comment by JohnMBrooks** [comment]
This is by-design, but I hope to improve it assuming I can find the code space.

The change to >2 drives per slot means that Bitsy Bye now does a 'next-drive' scan (tab key) when a slot number key is pressed multiple times. When next-drive reaches the last drive of a slot, it goes to drive 1 of the next lower slot.

**Comment by bobbimanners** [comment]
One idea, now we have more drives per slot ... The number key cycles forwards.  Could <Shift>+number key cycle back?  Otherwise this behaviour is super annoying.  Slot 6 drive 1 is usually empty in my day to day use.

Edit: I really like the >2 drives per slot change though!

**Comment by JohnMBrooks** [comment]
I think the best way to solve this in BB is for the 1-7 keys to toggle between drive 1 & drive 2 of the slot like P8 2.4.

The TAB key can then be used to cycle through drives 3-8 of the current slot.

**Comment by JohnMBrooks** [comment]
Fixed in 2.5.0a6
