### ISSUE TITLE
P8 2.5a6/BASIC.system crashes in AppleWin

### ISSUE THREAD

**Issue by LuiZ-80** [ProDOS-8/ProDOS8-Testing#26]
Both ProDOS 2.5a6 and BASIC.system crash in AppleWin

BUG

ProDOS 2.5 alpha 6
## Description

P8 itself appears to actually boot, but it appears to crash when starting BASIC.system, and then it drops me to the monitor _(if AppleWin is emulating an enhanced IIe)_ or leaves me on a blank screen (if it's emulating anything else). 

For curiosity's sake, I've tried different combinations of ProDOS and BASIC.SYSTEM. P8 2.5a6 loads previous BASICs successfully, but the BASIC replies to every disk/file command such as "CAT" or "CATALOG" with "FILE NOT OPEN", though regular BASIC programs that don't call on any disk routines, like a simple HELLO WORLD program, work fine.

Interestingly enough, I had to resort to using actual PRODOS utilities to create these mixed boot disks, as Ciderpress often crashed when trying to copy/paste ProDOS or BASIC.system between disk images. Also of note is that I've tried sending the stock alpha6 disk image to my enhanced Apple //e using ADTPRO,  but the transfer always fails with multiple errors when transferring the last 40 or so blocks. This would perhaps imply some issue with my host (Windows PC) machine somehow corrupting these files, but it works flawlessly on any other disk image, including transfer to the Apple. Accounting for that, I have tried booting a freshly downloaded copy of the stock P8 2.5a6 disk image on AppleWin on a second Windows computer, with the same results (crashing to the monitor)

## Steps to Reproduce
1. Boot ProDOS 2.5a6
2. Launch BASIC.System
3. Drops to the Monitor

## Your Environment

Windows 10 64bit host computers, AppleWin 1.28 and 1.29.

### Hardware:
AppleWin emulated Apple IIe Enhanced

### ProDOS8 version:

2.5 alpha 6

### Non-Operating System release software being used: 
BASIC.System 1.7a10

**Comment by LuiZ-80** [comment]
I neglected to mention that the latest alpha version that runs without any issues on AppleWin is 2.5a4, with BASIC.System 1.7a9. Any regression must have creeped in between alpha 4 and alpha 5.

**Comment by DevoKun** [comment]
Hello, @LuiZ-80 .
Thank you for your error report.
Do you mind performing one more test?
Could you please try **ProDOS 2.5a6** with **BASIC.System 1.7a9** from the 2.5a4 release ?
Thank you for your help with testing ProDOS 8.
Cheers,

**Comment by LuiZ-80** [comment]
Updating to say that I have tested ProDOS 2.5a6 with BASIC.System 1.7a9 from the 2.5a4 release, to the same result, crashing to monitor immediately after the ProDOS splash (if AppleWin is emulating an enhanced IIe), or dropping me to a completely blank screen if emulating an unenhanced IIe or an earlier machine. 
I'm attaching a screenshot of the monitor and of AppleWin's included debugger at the point of the crash,
![applewincrash](https://user-images.githubusercontent.com/56095417/66264235-dcce4000-e7d7-11e9-8447-6393b915ebe8.jpg)
![debugger](https://user-images.githubusercontent.com/56095417/66264237-e35cb780-e7d7-11e9-8748-f50f99ee3866.jpg)

**Comment by tomcw** [comment]
I've just released a new AppleWin 1.29.3.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0).

NB. The P8-2.5.0-alpha6 & AppleWin 1.29.3.0 status is:
- Enhanced //e (65C02): now works
- //e or II+ or II (6502) with Apple LC: hangs during boot
- II+ or II (6502) with Saturn "LC": works

I'm expecting John to release a new P8-2.5.0 that fixes the issue with the 6502-based machines.

**Comment by JohnMBrooks** [comment]
P8-2.5.0-alpha7 should now correctly enable LC write on 6502-based systems. It also includes a new Copy II+ 8.5 alpha 1.

https://drive.google.com/open?id=1n6ksz5DPddFRx3f0swJV2xcNwdKKIAL_

**Comment by tomcw** [comment]
Thanks John. I quickly tested booting with AppleWin 1.29.3 using models: Enh //e (65C02), //e (6502) and II+ (6502)... all boot OK.
