### ISSUE TITLE
Device Enumeration with more then 8 volumes on CFFA

### ISSUE THREAD

**Issue by patrickbst** [ProDOS-8/ProDOS8-Testing#33]
Testing a8 with multiple devices/volumes to test new drive table/device enumeration .  GS with CFFA in 7, SCSI in 4, single 5.25 in 6, single 3.5 in 5, ram disk set (appears as 5,2).  Set CFFA to 10 SP devices (no floppy).  SCSI in 4 had 4 vols.   Using A2osX to test (it natively supports lots of devs and lowercase).  15 devs/vols appeared (so confirmed a8 doing more then 14 of 2.03), but only 8 of the 10 CFFA vols were available.  I would have expected the 8 on slot 7 and then the other 2 to appear on slot 1?

**Comment by JohnMBrooks** [comment]
P8 2.5 only mounts volumes 1-8 on each slot card by-design. This allows disks and images to be freely mounted and unmounted without rebooting, unlike earlier versions of P8 which only mount/map volumes at ProDOS startup and had a somewhat unpredictable mapping scheme.

**Comment by patrickbst** [comment]
This probably should just be noted as expected behavior.  MicroDrive Turbo can have 2 CFs with 4 parts each, so 8 total so it should be OK.  Booti I think maxes at 8 so ok too.  FloppyEmu supports only 4 SP though someone should test what happens since it would be both a floppy and 4 hd on a liron/SP controller.  CFFA will be 1 thing affected as it could have up to 14 or 16 set in its control panel (people will have to limit to 8) and those with SCSI (especially with multiple drives, ok REALLY rare) could have more then 8 vols on that single control.
