### ISSUE TITLE
PRODOS ERR=4 on unenhanced //e using SVD drive emulator

### ISSUE THREAD

**Issue by tomcw** [ProDOS-8/ProDOS8-Testing#41]
## Description
Boot ProDOS_2_5_a8_143k.dsk using SVD drive emulator and it hangs with:
```
PRODOS ERR=4
..
```
Where "ERR" is flashing, and "=4" is inverse.

## Expected Behavior
ProDOS should boot.

## Actual Behavior
Hangs as in description.

## Steps to Reproduce
1. Boot ProDOS_2_5_a8_143k.dsk
2. Also booting ProDOS_2_5_a4_143k.po produced the same error message and hang.

### Hardware:
Real hardware
PAL Unenhanced Apple IIe w/ Extended 80 Column Card
Disk II card connected to an SVD (Semi Virtual Diskette) drive emulator - see http://thesvd.com/.

NB. Under AppleWin emulation and similar emulated h/w (PAL Unenhanced Apple IIe w/ Extended 80 Column Card), then this DSK boots fine. So perhaps it's the boot code doing something funky that the SVD drive emulator doesn't like?

### ProDOS8 version:
2.5.0a8 or 2.5.0a4 (but I've not tried any other versions)

**Comment by JohnMBrooks** [comment]
Hi Tom, it looks like the SVD card is not 100% compatible with the Disk ][ which is the likely cause of this error.

The new ProDOS 2.5 boot loader steps the head through 1/4 tracks and 1/2 tracks, and so requires 5.25 drives with 1/4 track compatibility. The SVD page for Apple II states that the SVD drive is currently incompatible with half-track seeks.

-JB

**Comment by tomcw** [comment]
Hi John - yep, your explanation makes sense. Please close as invalid.

**Comment by JohnMBrooks** [comment]
Okay. BTW, P8 2.5.x will boot using older boot blocks, so if you copy 2.4 boot blocks to P8 2.5.x it may boot on SVD.

-JB
