### ISSUE TITLE
P8 2.4.2 loses a floppy volume

### ISSUE THREAD

**Issue by roughana** [ProDOS-8/ProDOS8-Testing#50]
## Description
I load two floppies into Slot 6,d1: Prodos 2.4.2 distribution
& slot 6,d2: https://github.com/jeremysrand/a2bejwld/releases/download/2.6/a2bejwld.dsk
Boot P8 2.4.2 into Bitsy Bye. S6,D1 volume name & content is displayed
Press Tab. S6,D2 volume name & content is displayed
Press Tab. S3,D2 volume name & content is displayed (empty)
Press Tab. S6,D1 volume name is displayed, but the content of the file list is the content from S6,D2

## Expected Behavior
File list should be the content from S6,D1

## Your Environment
In Applewin 1.29.12.0 and MAME 200_2018-08-21, with configuration as Apple //e
Here's my MAME startup command:
mame64 -w apple2ee -sl6 diskii -flop1 "ProDOS_2_4_2.dsk" -flop2 "a2bejwld_SAM.dsk" 

### ProDOS8 version:
P8 2.4.2

**Comment by roughana** [comment]
Further, I started bejwelled, then quit to bitsy bye. S6,d2 volume and content was displayed.
I tabbed to 3,2 & 6,1 and content displayed is S6,d1
I tabbed to 6,2 and content displayed is S6,d1.
I started BASIC.SYSTEM & did PREFIX,S6,D2 and then did CATALOG.
Content displayed is S6,d1.

So the problem appears to be with P8 2.4.2 internals rather than Bitsy Bye.

**Comment by uberRegenbogen** [comment]
Duplicated under AppleWin 1.29.3.0.
Does not occur in ProDOS 8 2.5.0a8 or 2.5.0a2.

**Comment by roughana** [comment]
Is this caused by the VCB related bug? https://github.com/ProDOS-8/ProDOS8-Testing/issues/46

**Comment by JohnMBrooks** [comment]
I suspect this is the VCB bug that was fixed in 2.5. I need to backport the fix to 2.4 along with some improvements and release 2.4.3.

**Comment by JohnMBrooks** [comment]
Fixed in 2.4.3
