### ISSUE TITLE
On //e ProDOS 2.5.0.a2 Bitsy Bye locks up if 'Delete' key is pressed

### ISSUE THREAD

**Issue by joelmcw** [ProDOS-8/ProDOS8-Testing#6]
Bitsy Bye locks up on //e when Del key is pressed

Bug

## Description

On //e Bitsy Bye locks up if 'Delete' key is pressed

## Expected Behavior

Should be able to select progams to run, tab to other volumes, etc

## Actual Behavior

After booting ProDOS 2.5.0.a2 Bitsy Bye loads and works fine until 'Delete" key is pressed then the system locks up

## Steps to Reproduce

1. Boot ProDOS 2.5.0.a2
2. Press 'Delete" key
3. Attempt to tab to another volume or select a file to run
4.

## Context

Looking for issues with this new Alpha release

### Hardware:

Apple //e Platinum, 80col, 4Mb Ramworks III, Fastchip //e, Super Serial, VidHD, CFFA3000

### ProDOS8 version:
2.5.0.a2

### Non-Operating System release software being used: 
The new Bitsy Bye

**Comment by JohnMBrooks** [comment]
Nice find! Fixed in 2.5.0.a3.
