### ISSUE TITLE
Beagle Bros ProgramWriter missing memory on newer ProDOS versions

### ISSUE THREAD

**Issue by jblang** [ProDOS-8/ProDOS8-Testing#61]
TITLE: Beagle Bros ProgramWriter missing memory on newer ProDOS versions
LABEL: BUG
PROJECT:  ProDOS 2.4.2

## Description

[Beagle Bros ProgramWriter](http://beagle.applearchives.com/the_software/the_timeout_series/program_writer.html) is incorrectly detecting free memory with ProDOS 2.4.2.  It comes on a ProDOS 1.8 disk and from that disk, I see 24K free using EDITOR and 34K using EDITOR.LC, which loads into the language card.  With ProDOS 2.4.2 I get only 6.8K on EDITOR.LC, and EDITOR will not even load.  I also see the same on ProDOS 2.0.3. This happens whether BITSY BYE is used or not.  I believe this is probably a bug in ProgramWriter but I was hoping maybe there is some fix that can be applied in ProDOS or a suggested workaround.  This happens on AppleWin as well as my real hardware.

## Expected Behavior
Expect to see 24K free using EDITOR and 34K using EDITOR.LC.

## Actual Behavior
I get only 6.8K on EDITOR.LC, and EDITOR will not even load

## Steps to Reproduce
1. Download ProDOS 2.4.2 disk
2. Delete extra files (e.g., COPY II PLUS, Cat.Doctor, etc.)
3. Download ProgramWriter disk (link above)
4. Copy files from ProgramWriter disk to ProDOS 2.4.2 disk (I used CiderPress for steps 3-4)
5. Boot disk and go into Applesoft BASIC.SYSTEM
6. Load Editor (-EDITOR.LC) and launch using &&
7. Note only 6.9K FREE memory

## Context
Unable to use ProgramWriter with ProDOS 2.4.2.

## Your Environment
wDrive floppy emulator
SoftSP ROM Card

### Hardware:
128K enhanced IIe

### Non-Operating System release software being used: 

Beagle Bros ProgramWriter

**Comment by jblang** [comment]
I found a disk image called ProgramWriter 2.0 on asimov and it works correctly with Prodos 2.4.2. Oddly, I found no mention of it on the Beagle Bros website, and on Alan Bird's site he explicitly says there was no 2.0:

>An editor that used the familiar AppleWorks interface for full-screen editing of BASIC programs. This is the only application that never went beyond version 1.0 as no bugs were ever discovered and it was full-featured right from the start. This product was later published by Beagle Bros. Looking back, I should have thought of a more clever name for this product.

Maybe someone else patched it...

In any case I'm closing this since I have a solution and this isn't really a ProDOS problem.

**Comment by DevoKun** [comment]
@jblang , thanks for reporting this issue. I'm glad that you were able to find a compatible version of **ProgramWriter**.

Your issue report inspired me to add an [application compatibility list to the ProDOS website](https://prodos8.com/applications/).

[If you find some compatibilities in the future, good or bad, please feel welcome to contribute them to our list.](https://github.com/ProDOS-8/ProDOS-8.github.io/blob/master/_pages/applications.md)
