### ISSUE TITLE
Y2K bug issue in ProDOS

### ISSUE THREAD

**Issue by wyatt-wong** [ProDOS-8/ProDOS8-Testing#62]
Y2K bug issue in ProDOS

## Description

Someone raised a concern of Y2K bug issue in the Apple II Enthusiasts Facebook Group (see below). 

```
Since it came up indirectly in another thread…

How did you all get around the Y2K “virus”/“bug” in the Apple II, and was it the same in all versions?

I had two different computers (neither Apple, both HP) at the time, and the only thing I had to do was, 
on the older one, change “01-01-100” to “01-01-2000” and save the date; the newer one was set up 
to deal with the change without problems or changes.
```

Another person provide the following URL and stated that ProDOS can handle 1940 - 2039
http://www.1000bit.it/support/manuali/apple/technotes/pdos/tn.pdos.28.html

So is there any consideration of solving Y2K issue in ProDOS ?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by DevoKun** [comment]
Hello, @wyatt-wong .
Please post the full details of the issue being experienced for those without Facebook access.
Thank you.

**Comment by inexorabletash** [comment]
The context was primarily humorous, but I think @wyatt-wong took it seriously. A poster entirely unfamiliar with the Apple II ecosystem was asking if there were Y2K problems. I replied with the technote link given above in jest, as that presumably represents Apple's only official statement about Y2K problems for the Apple II. 

The ProDOS 2.5 effort does introduce support for a wider range of dates, at the expense of requiring application updates. Of course, those app updates would also be needed for apps that adopted the technote recommendation of treating dates 00-39 as 21st Century instead. 

I think you can safely close this issue.

**Comment by inexorabletash** [comment]
(2.4.2's table for the Thunderclock driver will need an update in a year or two, but that's a different problem.)

**Comment by wyatt-wong** [comment]
> The context was primarily humorous, but I think @wyatt-wong took it seriously. A poster entirely unfamiliar with the Apple II ecosystem was asking if there were Y2K problems. I replied with the technote link given above in jest, as that presumably represents Apple's only official statement about Y2K problems for the Apple II. 
> 
> 
> 
> The ProDOS 2.5 effort does introduce support for a wider range of dates, at the expense of requiring application updates. Of course, those app updates would also be needed for apps that adopted the technote recommendation of treating dates 00-39 as 21st Century instead. 
> 
> 
> 
> I think you can safely close this issue. 

If you think I posted this issue is humorous, you can inform the admin and/or moderator to close it. But I would suggest you to be polite when you reply my post.

**Comment by inexorabletash** [comment]
I apologize, I was unclear. I believe that @wyatt-wong's posting here was entirely serious, and a sincere effort to report what they perceived as a potential problem. I only meant to highlight that it was inspired by discussions on FB by others (including myself) that were not serious.

**Comment by wyatt-wong** [comment]
> Hello, @wyatt-wong . Please post the full details of the issue being experienced for those without Facebook access. Thank you.

I have updated my post to include the details from the Facebook post.

**Comment by DevoKun** [comment]
The Thunderclock driver was updated in ProDOS 2.4.3 to work past the year 2023.
