### ISSUE TITLE
Volume Issue with new Yellowstone UDC

### ISSUE THREAD

**Issue by joelmcw** [ProDOS-8/ProDOS8-Testing#63]
ProDOS/BitsyBoot issue with new Yellowstone UDC

Bug

2.4
## Description

I have a fully populated //e Platinum (see hardware description)

I'm currently running 2 HD volumes on the CFFA which get mapped to S7,D1 & S7,D2. I have one physical 5.25 drive (attched to YS UDC drive 1 connector) which is mapped as 6,1 and I have 2 Unidisk 3.5 drives attached to the YS UDC drive 2 connector (daisychained) so they are mapped as S6,D2 and S4,D1 by ProDOS. My CFFA virtual Disk IIs are mapped as S5,D1 & S5,D2.

After booting ProDOS, I can cycle through all the volumes with the tab key in Bitsy Bye and can see all of the drive mappings and can execute the programs on all volumes including S4,D1. However, if I try to boot S4,D1 with Bitsy Boot, it crashes to the monitor.  From ProDOS I can catalog S4,D1 and execute programs however I cannot boot with PR#4 or with C400G from the monitor.

Additionally, Running ADTPro 2.10 I've found what I believe is a related issue. It can see the volume name in S4,D1 but if I attempt to format the 3.5 disk I get "NO UNIT IN THAT SLOT AND DRIVE". I suspect it is getting this info from ProDOS.

I've also seen this same behavior with a different configuration, for example, 3 CFFA smartport HD volumes and with 5.25 daisychained behind a single 3.5 Unidisk on YS UDC drive 1 connector and nothing on the drive 2 connector.  This results in similar drive mappings except the 5.25 is mapped as S6,D1 and the 3.5 is S6,D2 and the CFFA volumes S7,D1 S7,D2, S4,D1.  Bitsy Bye still crashes to the monitor if I try to boot S4,D1.

Also, same exact results with enhanced Apple //e, 80 col RAM card, Super Serial, and Yellowstone disk controller (no CFFA, VidHD, FastChip, or MB). 5.25 drive on primary connector and mapped to S6,D1. 3.5 Unidisk (with a second 3.5 Unidisk daisychained) attached to secondary connector mapped to S6,D2 and S4,D1 respectively. 

## Expected Behavior

I should be able to successfully boot all mapped disk volumes from BitsyBoot or from ProDOS.

## Actual Behavior

Crashes to the monitor instead of booting from BitsyBoot.  No Device Connected trying to boot from ProDOS.

## Steps to Reproduce

1.  Boot system from CFFA volume
2.  From BitsyBye view mapped volumes
3.  Attempt boot S4,D1
4.  

## Context

The user should be able to boot any available D1 volume

### Hardware:

Apple //e Platinum with the following configuation:
Slot 7 - CFFA3000
Slot 6 - Yellowstone UDC
Slot 5 - Virtual floppy drive (CFFA)
Slot 4 - Mockingboard
Slot 3 - VidHD
Slot 2 - Super Serial
Slot 1 - Fastchip //e
Slot 0 (Aux) - GW8RAM (emulating Ramworks III)

### ProDOS8 version:
2.4.2

### Non-Operating System release software being used: 
ADTPro

**Comment by JohnMBrooks** [comment]
The Apple II, and ProDOS can only boot the the physical slot of the disk controller card, and will only boot drive 1 of that controller. There are a few cards (like CFFA), which mimic an additional 2nd controller card, and so will let you boot drive 1 of the physical card (ie CFFA slot, drive 1 as a bootable hard drive), and the mimic card (ie, Disk ][ controller in slot 6).

The 3.5" drive you see mapped to slot 4 by ProDOS 2.x is neither a physical controller nor a mimic controller in slot 4, and so cannot be booted.

See Apple's tech note ProDOS #23 under the 2.0.1 release and bugs sections for some more info about the ProDOS 2.x volume remapping scheme:
http://www.1000bit.it/support/manuali/apple/technotes/pdos/tn.pdos.23.html

**Comment by joelmcw** [comment]
Ok, this is good info. Thanks John!
