### ISSUE TITLE
ProDOS 2.5.0a2 and ShrinkIt v3.4 NO BUFFERS AVAILABLE

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#7]
ProDOS 2.5.0a2 can't load ShrinkIt v3.4

2.5.0

## Description

When I open Shrinkit v3.4 in ProDOS 2.5.0a2 it fails to load with NO BUFFERS AVAILABLE

## Expected Behavior

Should load.

## Actual Behavior

Ain't no buffers!

## Steps to Reproduce

Just try to run the ShrinkIt v3.4 app.  Works in ProDOS 2.5.2 and 2.5.1.
I can provide a copy of the failing app in case you can't reproduce this.

**Comment by bobbimanners** [comment]
Actually this only happens when I start ProDOS 2.5.0a2 by running the PRODOS file from within ProDOS 2.4.2.  If I boot from ProDOS 2.5.0a2 it does not occur, so maybe this is not an issue.  Seems like rather weird behaviour though.

**Comment by bobbimanners** [comment]
Maybe I will re-open this just so John sees it.

**Comment by JohnMBrooks** [comment]
I was unable to repro by booting P8 2.5.0a3 and running Shrinkit 3.2. Please see if you can repro using P8 2.5.0a3:

https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP

**Comment by bobbimanners** [comment]
I only observed this happening in the weird case where I boot 2.4.2 and then switch to 2.5.0a2 by running it's PRODOS.SYSTEM file.  It doesn't happen if you boot 2.5.0a2 directly.  I am not sure if booting one version and switching like this is really a supported use-case though.  If not, then this ticket can just be closed as 'problem between chair and keyboard.' :)

Nonetheless, I will try with 2.5.0a3 this evening.

**Comment by bobbimanners** [comment]
Here is the troublesome file, as-is (uploaded from Apple II using zmodem)
and as a ShrinkIt archive.

All the best,
Bobbi

**Comment by JohnMBrooks** [comment]
Unable to repro in P8 2.5.0a4 when booting 2.4.2, then running 2.5.0a4, then Shrinkit. May be related to corrupt vol names in ONLINE calls.
