### ISSUE TITLE
ProDOS.FX QUIT code not displaying all files

### ISSUE THREAD

**Issue by rallepalaveev** [ProDOS-8/ProDOS8-Testing#70]
The ProDOS.FX and ProDOS 2.0.3 QUIT code seems to be displaying folders and SYSTEM files ($FF), which can be executed, while other executable files like BIN and BAS are not displayed and cannot be executed.

Propose to add to the files being displayed types $06, $FA, $FC and $FD.

Thank you.

**Comment by JohnMBrooks** [comment]
Please report ProDOS.FX issues to the A2osX GitHub, as A2osX is a separate project and dev team from ProDOS-8:
https://github.com/A2osX/A2osX/issues

**Comment by rallepalaveev** [comment]
I did and was referred here. But I will take it back to that project - thanks!

**Comment by JohnMBrooks** [comment]
I see. Have you tried ProDOS 2.4.2 which has several improvements over ProDOS 2.0.3? P8 2.4.2 has a new QUIT program selector called Bitsy Bye which allows launching BIN and BAS files as long as there is a BASIC.SYSTEM or BASIS.SYSTEM in the root directory. Bitsy Bye also allows launching Apple IIGS S16 files if ProDOS was run from GS/OS.

**Comment by rallepalaveev** [comment]
Oh certainly, I have been using P8 2.4.2 regularly and I am quite happy with Bitsy Bye and in general how it works. I just decided to try out A2osX and while attempting to fit it in a smaller image file for the hardware I am developing, I encountered some issues like small letters and leading dot, so then I found out P.FX was used and reported the issue that I found.
