### ISSUE TITLE
ThunderClock driver update needed for 2024+

### ISSUE THREAD

**Issue by inexorabletash** [ProDOS-8/ProDOS8-Testing#72]
The ThunderClock system clock card provides day, month and day-of-week but not year. From those, the ProDOS driver infers the year using a table. But the table only handles a range of 6 or 7 years. 

If I recall correctly, the updated table in ProDOS 2.4.2 expires after 2023, so as of 1/1/2024 users will start seeing incorrect dates in ProDOS, if they're using the ThunderClock or compatibles. 

This doesn't affect drivers for clocks that have the year (e.g. the built in IIgs clock driver, third party No-Slot-Clock driver, etc) so it's not a huge deal.

**Comment by inexorabletash** [comment]
I just double checked and... yeah, 2.4.2 has this table:

For 2018 - 2023: $12, $17, $16, $15, $14, $14, $13

If it helps, one of the following tables could be patched in:

For 2023 - 2028: $18, $17, $1C, $1B, $1A, $19, $18
For 2024 - 2028: $18, $1C, $1C, $1B, $1A, $19, $18

**Comment by JohnMBrooks** [comment]
Fixed in 2.4.3
