### ISSUE TITLE
2.5.0a2 Bitsy Bye letter-seek doesn't find lowercase

### ISSUE THREAD

**Issue by uberRegenbogen** [ProDOS-8/ProDOS8-Testing#8]
## Description
ProDOS 8 2.5.0a2's Bitsy Bye's first-letter-seek doesn't find items that start with a lowercase letter.

## Expected Behavior
Pressing a letter should jump to the next item starting with that letter—upper or lowercase.

## Actual Behavior
Items starting with lowercase letters are not matched.

## Possible Fix
Force case of item name letter to be compared to key.

## Steps to Reproduce

1. Invoke Bitsy bye
2. Press first letter of an item that starts with a lowercase letter.

## Context
Minor inconvenience.

### Hardware:
GSplus; AppleWin

### ProDOS8 version:
2.5.0a2

**Comment by JohnMBrooks** [comment]
Good catch! Fixed in 2.5.0a3.
