### ISSUE TITLE
Kyan Pascal issues with ProDOS 2.5.0a2

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#9]
Kyan Pascal issues with ProDOS 2.5.0a2

BUG

2.5.0
## Description

Attempt to run Kyan Pascal from hard drive install fails on 2.5.0a2, but same installation is fine with 2.4.2.

When KIX.SYSTEM is first run it seems to be okay - the intro text is displayed as normal.  Hit <Return> to start the shell and things fall to pieces.  Normally one gets an 80 column display with a '%' prompt, but with 2.5.0a2 it drops to a corrupt 40 column screen.  The shell is actually running so I tried the 'c80' command to switch to 80 columns.  This cleared up the garbage from the screen, but remained in 40 column mode.  Everything works fine when I go back to 2.4.2.

## Expected Behavior

Should be 80 cols not 40 cols.

## Actual Behavior

40 column screen with corruption.

## Steps to Reproduce

1. Boot 2.5.0a2
2. Run KIX.SYSTEM from Kyan Pascal using Bitsy Bye
3. Hit <Return> after the intro text is displayed

## Context

I need my Pascal fix!

### Hardware:

Apple //e Enhanced, 128K, MicroDrive/Turbo in slot 7.

### ProDOS8 version:
2.5.0a2

### Non-Operating System release software being used: 
Kyan Pascal

**Comment by JohnMBrooks** [comment]
Nice find. Fixed in 2.5.0a3

https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP

**Comment by bobbimanners** [comment]
Thanks John!!  I will re-test this evening with 2.5.0a3.  Fast work!!
